### PR TITLE
Update chat handle

### PR DESCRIPTION
**Pull request by ryjones**

### CODE REVIEW

**Comment by heatherlp** [comment]
Hey @ryjones, why are you changing the chat handle? Have I missed something about us moving away from RC?

**Comment by ryjones** [comment]
> Hey @ryjones, why are you changing the chat handle? Have I missed something about us moving away from RC?

Hi! Gari's chat handle is the one I put in there, not the one that was in the file. That's all.

**Comment by heatherlp** [comment]
Yeah, sure. I meant the change from "RocketChat" -> "Chat"? On line 5

**Comment by ryjones** [comment]
ah - that's a personal pet peeve of mine. We're not moving on from Rocket.Chat.

**Review by heatherlp — APPROVED** [review]
LGTM, but the tests are failing to pull docker images - is nexus down?

**Comment by ryjones** [comment]
@btl5037 is this an issue with the nexus transition?

**Comment by btl5037** [comment]
Nope, the image probably aged out of Nexus (if we don't update the repo in 30 days, the image ages out, not sure where that policy started but we hit it all the time)

**Comment by btl5037** [comment]
Still working on this Nexus is giving me a hard time

**Pull request merged**
