### PR TITLE
Fix some wrong spelling and url in the README.md

### PR DESCRIPTION
**Pull request by nadongjun**
Signed-off-by: nadongjun aa9814526@gmail.com

### CODE REVIEW

**Review by bestbeforetoday — CHANGES_REQUESTED** [review]
Since you're changing the URL, **nodei.co** doesn't look like the right place for us to be going. Direct to `https://www.npmjs.com/package/fabric-ca-client` would be better, and is where **nodei.co** redirects to

**Comment by nadongjun** [comment]
I changed the url to "https://www.npmjs.com/package/fabric-ca-client"

**Comment by nadongjun** [comment]
> Since you're changing the URL, **nodei.co** doesn't look like the right place for us to be going. Direct to `https://www.npmjs.com/package/fabric-ca-client` would be better, and is where **nodei.co** redirects to

I changed the url to "https://www.npmjs.com/package/fabric-ca-client"

**Review by bestbeforetoday — APPROVED** [review]
Thank you for the contribution!

**Pull request merged**
