### PR TITLE
[FABN-1407] Add PDC and EP types (1.4)

### PR DESCRIPTION
**Pull request by sstone1**
Add typings for a private data collection configuration
and endorsmeent policy to ChaincodeInstantiateUpgradeRequest.

Signed-off-by: Simon Stone <sstone1@uk.ibm.com>
Change-Id: I32f1789dbb96fecc88d03fcd841356d21fcb89e9

### CODE REVIEW

**Comment by bestbeforetoday** [comment]
This should really go into _master_ first

**Comment by davidkhala** [comment]
package.json#scripts.retrieve-images is missing for release-1.4 but existing in master branch
Curious why trigger a master builder

**Pull request merged**
