### PR TITLE
update to x509 0.4.7

### PR DESCRIPTION
**Pull request by mbwhite**
Signed-off-by: Matthew B White <whitemat@uk.ibm.com>

### CODE REVIEW

**Comment by heatherlp** [comment]
https://github.com/hyperledger/fabric-sdk-node/pull/33 - this is merged and I stole your changes so this can be abandoned

**Comment by davidkhala** [comment]
@mbwhite when I trying `npm install` with dependencies including `fabric-client 1.4.4`
in nodejs `10.17 ` environment, 
I see 
```
> x509@0.3.4 install ***/node_modules/x509
> node-gyp rebuild
make: Entering directory '***/node_modules/x509/build'
  CXX(target) Release/obj.target/x509/src/addon.o
  CXX(target) Release/obj.target/x509/src/x509.o
../src/x509.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE verify(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/x509.cc:55:65: warning: ‘v8::String::Utf8Value::Utf8Value(v8::Local<v8::Value>)’ is deprecated: Use Isolate version [-Wdeprecated-declarations]
   std::string cert_path = *String::Utf8Value(info[0]->ToString());
```
Is this patch helpful to my issue?

**Comment by mbwhite** [comment]
Hello; yes I believe it might be;
 
The aim was to remove the deprecation warnings from the `@ampretia/x509` library
 
 
Regards, Matthew. 
Matthew B White  IBM Blockchain Solutions Architect
 
Email me at WHITEMAT@uk.ibm.com
Find me on StackOverflow, and generally at  calanais.me.uk
 
Note: restricted availability for meetings 14:30 to 17:00 UK Tuesday 
IBM United Kingdom Limited, Hursley Park, Winchester, Hampshire, SO21 2JN
"The wrong answers are the ones you go looking for when the right answers stare you in the face" 
 
 
----- Original message -----From: Yuxiang LIU <notifications@github.com>To: hyperledger/fabric-sdk-node <fabric-sdk-node@noreply.github.com>Cc: Matthew B White <whitemat@uk.ibm.com>, Author <author@noreply.github.com>Subject: [EXTERNAL] Re: [hyperledger/fabric-sdk-node] update to x509 0.4.7 (#34)Date: Fri, Nov 22, 2019 7:28 AM 
@mbwhite when I trying npm install with dependencies including fabric-client 1.4.4in nodejs 10.17  environment,I see
> x509@0.3.4 install ***/node_modules/x509> node-gyp rebuildmake: Entering directory '***/node_modules/x509/build'  CXX(target) Release/obj.target/x509/src/addon.o  CXX(target) Release/obj.target/x509/src/x509.o../src/x509.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE verify(Nan::NAN_METHOD_ARGS_TYPE)’:../src/x509.cc:55:65: warning: ‘v8::String::Utf8Value::Utf8Value(v8::Local<v8::Value>)’ is deprecated: Use Isolate version [-Wdeprecated-declarations]   std::string cert_path = *String::Utf8Value(info[0]->ToString());
Is this patch helpful to my issue?
—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
 Unless stated otherwise above:
IBM United Kingdom Limited - Registered in England and Wales with number 741598. 
Registered office: PO Box 41, North Harbour, Portsmouth, Hampshire PO6 3AU

**Comment by mbwhite** [comment]
@heatherlp abandoning... :-)

**Comment by davidkhala** [comment]
> Hello; yes I believe it might be;   The aim was to remove the deprecation warnings from the `@ampretia/x509` library     Regards, Matthew. Matthew B White  IBM Blockchain Solutions Architect   Email me at WHITEMAT@uk.ibm.com Find me on StackOverflow, and generally at  calanais.me.uk   Note: restricted availability for meetings 14:30 to 17:00 UK Tuesday  IBM United Kingdom Limited, Hursley Park, Winchester, Hampshire, SO21 2JN "The wrong answers are the ones you go looking for when the right answers stare you in the face"      ----- Original message -----From: Yuxiang LIU <notifications@github.com>To: hyperledger/fabric-sdk-node <fabric-sdk-node@noreply.github.com>Cc: Matthew B White <whitemat@uk.ibm.com>, Author <author@noreply.github.com>Subject: [EXTERNAL] Re: [hyperledger/fabric-sdk-node] update to x509 0.4.7 (#34)Date: Fri, Nov 22, 2019 7:28 AM  @mbwhite when I trying npm install with dependencies including fabric-client 1.4.4in nodejs 10.17 environment,I see
> ***@***.*** install ***/node_modules/x509> node-gyp rebuildmake: Entering directory '***/node_modules/x509/build'  CXX(target) Release/obj.target/x509/src/addon.o  CXX(target) Release/obj.target/x509/src/x509.o../src/x509.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE verify(Nan::NAN_METHOD_ARGS_TYPE)’:../src/x509.cc:55:65: warning: ‘v8::String::Utf8Value::Utf8Value(v8::Local<v8::Value>)’ is deprecated: Use Isolate version [-Wdeprecated-declarations]   std::string cert_path = *String::Utf8Value(info[0]->ToString());
> Is this patch helpful to my issue? —You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.  Unless stated otherwise above: IBM United Kingdom Limited - Registered in England and Wales with number 741598. Registered office: PO Box 41, North Harbour, Portsmouth, Hampshire PO6 3AU

I found it is due to my project dependency conflicts instead of fabric-sdk-node itself, so I deleted my spamming reply :-)

**Pull request closed without merging**
